<?php

$others  = [
	[
        'Others',
        'child' => [                
          ['Husk(Bhushi)'],
          ['Firewood'],
          ['Live Animal'],          
          ['Sugar'],
          ['Salt'],        
          ['Molasses (Gur)'],
          ['Chicken'],
          ['Pulses'],
          ['Jute'],
          ['Vegetables'],
          ['Fish'],
          ['Cattle'],
          ['Milk'],
          ['Egg'],
          ['Tin'],
          ['Timber'],
          ['Bamboo'],
          ['Cloths'],
          ['Sugar Cane'],
          ['Wood'],
          ['Fuel'],
          ['Fish Food'],
          ['Sowmill'],
          ['Sweet Potato'],
          ['Dal'],
          ['Goat'],
          ['Muri'],
          ['Flower'],
          ['Peaple'],
          ['Chick'],
          ['Epot'],
          ['Apot'],
          ['Gur'],
          ['Mat'],
          ['Bunt'],
          ['Mastqt'],
          ['Cow'],
          ['Peanut'],
          ['Oil Cake (Local)'],
          ['Oil Seed'],
          ['Mustered Seed'],
          ['Puleses Seed'],
       ]
     ], 
];