<?php

$vegetable  = [
	[
        'শাকসবজি',
        'child' => [                     
          ['আলু'],  
          ['বেগুন'],
          ['লাউ'],   
          ['শসা'],  
          ['শিম'], 
          ['লাল শাক'],
          ['পালং শাক'],
          ['পুই শাক'],
          ['লাউ শাক'],
          ['ডাটা  শাক'],
          ['সাদা শাক'],
          ['কুমড়া শাক'],
          ['সাদা শাক'],
          ['বাঁধাকপি'],
          ['ফুলকপি'],
          ['হলরবী'],
          ['চাইনিজ বাঁধাকপি'],             
          ['পেটসাই'],         
          ['সরিষা শাক'],
          ['শালগম'],
          ['মূলা'],
          ['ব্রাসেলস স্প্রাউট'],
          ['জল ক্রেস'],
          ['মটর'],
          ['হায়াসিন্ট শিম'],
          ['স্ট্রিং বিন'],
          ['ফরাসি শিম'],
          ['উইংড শিম'],
          ['তরোয়াল শিম'],
          ['শাকসবজি সয়াবিন'],
          ['পাঁচ শিম'],         
          ['ইয়াম শিম'],
          ['মিষ্টি লাউ'],
          ['গোল লাউ'],
          ['মোম করলা'],
          ['ছোট শশা'],          
          ['স্পঞ্জ লাউ'],
          ['তিতা লাউ'],
          ['চায়েলে লাউ'],
          ['পালভাল'],
          ['মিস্টি কুমড়া'],
          ['চাল কুমড়া'],
          ['চিচিঙ্গা'],
          ['স্কোয়াশ'],
          ['কস্তুরী'],         
          ['আইভরি লাউ'],
          ['স্ন্যাপ তরমুজ'],
          ['প্রাচ্য তরমুজ'],
          ['তরমুজ'],
          ['টমেটো'],
          ['মিষ্টি মরিচ'],
          ['ওকরা'],
          ['রোজেল'],
          ['স্টেম অ্যামেরেন্ট'],
          ['মরিচ'],          
          ['অন্যান্য'],                  
       ]
     ], 
];




// $vegetable  = [
// 	[
//         'Vegetable',
//         'child' => [                     
//           ['Potato'],  
//           ['Brinjal'],
//           ['Gourd'],   
//           ['Cucumber'],  
//           ['Beans'], 
//           ['Cabbage'],
//           ['Cauliflower'],
//           ['Kholrabi'],
//           ['Chinese cabbage'],             
//           ['Petsai'],
//           ['Saishin'],
//           ['Mustard green'],
//           ['Turnip'],
//           ['Radish'],
//           ['Brussels sprouts'],
//           ['Water cress'],
//           ['Pea'],
//           ['Hyacinth bean'],
//           ['String bean'],
//           ['French bean'],
//           ['Winged bean'],
//           ['Sword bean'],
//           ['Vegetable soybean'],
//           ['Lima bean'],
//           ['Tripatri leaves'],
//           ['Yam bean'],
//           ['Sweet gourd'],
//           ['Bottle gourd'],
//           ['Wax gourd'],
//           ['Cucumber (short)'],
//           ['Ribbed gourd'],
//           ['Sponse gourd'],
//           ['Bitter gourd'],
//           ['Teasle gourd'],
//           ['Palwal'],
//           ['Snake gourd'],
//           ['Squash'],
//           ['Muskmelon'],
//           ['Ivory gourd'],
//           ['Snap melon'],
//           ['Oriental melon'],
//           ['Watermelon'],
//           ['Tomato'],
//           ['Sweet pepper'],
//           ['Okra'],
//           ['Rozelle'],
//           ['Stem amaranth'],
//           ['Chilli'],
//           ['Stem amaranth'],
//           ['Red amaranth'],
//           ['Spiny amaranth'],
//           ['Leaf amaranth'],
//           ['Haicha'],
//           ['Others'],                  
//        ]
//      ], 
// ];