<?php

$vegetable  = [
	[
        'Vegetable',
        'child' => [                     
          ['Potato'],  
          ['Brinjal'],
          ['Gourd'],   
          ['Cucumber'],  
          ['Beans'], 
          ['Cabbage'],
          ['Cauliflower'],
          ['Kholrabi'],
          ['Chinese cabbage'],             
          ['Petsai'],
          ['Saishin'],
          ['Mustard green'],
          ['Turnip'],
          ['Radish'],
          ['Brussels sprouts'],
          ['Water cress'],
          ['Pea'],
          ['Hyacinth bean'],
          ['String bean'],
          ['French bean'],
          ['Winged bean'],
          ['Sword bean'],
          ['Vegetable soybean'],
          ['Lima bean'],
          ['Tripatri leaves'],
          ['Yam bean'],
          ['Sweet gourd'],
          ['Bottle gourd'],
          ['Wax gourd'],
          ['Cucumber (short)'],
          ['Ribbed gourd'],
          ['Sponse gourd'],
          ['Bitter gourd'],
          ['Teasle gourd'],
          ['Palwal'],
          ['Snake gourd'],
          ['Squash'],
          ['Muskmelon'],
          ['Ivory gourd'],
          ['Snap melon'],
          ['Oriental melon'],
          ['Watermelon'],
          ['Tomato'],
          ['Sweet pepper'],
          ['Okra'],
          ['Rozelle'],
          ['Stem amaranth'],
          ['Chilli'],
          ['Stem amaranth'],
          ['Red amaranth'],
          ['Spiny amaranth'],
          ['Leaf amaranth'],
          ['Haicha'],
          ['Others'],                  
       ]
     ], 
];